// Copyright 2022 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_COMPILER_CODEGEN_ACCEL_TRANSFORMEXTENSIONS_ACCELEXTENSIONS
#define IREE_COMPILER_CODEGEN_ACCEL_TRANSFORMEXTENSIONS_ACCELEXTENSIONS

include "mlir/Dialect/Transform/IR/TransformDialect.td"
include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.td"
include "mlir/Interfaces/SideEffectInterfaces.td"
include "mlir/IR/OpBase.td"

#endif // IREE_COMPILER_CODEGEN_ACCEL_TRANSFORMEXTENSIONS_ACCELEXTENSIONS
